### ISSUE TITLE
Captured images are dark and green

### ISSUE THREAD

**Issue by ShawnHymel** [edgeimpulse/firmware-espressif-esp32#3]
The preview seems in the live feed on a Studio project seems to show the correct lighting and white balance for an image. However, when I capture the image, it appears dark and green. Not sure where the brightness and white balance values are getting changed.

![esp32-brightness](https://user-images.githubusercontent.com/5232145/171263921-b6883e5a-5cc7-47d4-80fe-eadee44a07ac.png)

**Comment by AIWintermuteAI** [comment]
Issues reproduced and fixed. The fix will be published with next ESP32 firmware update.

**Comment by AIWintermuteAI** [comment]
Should be fixed after merging latest PR to our monorepo master. Fix will be in production within next few days. Feel free to re-open if issue persists.

**Comment by hayschan** [comment]
I encounter the exact same problem.

<img width="520" alt="image" src="https://user-images.githubusercontent.com/25737801/202981907-cd4304c8-17a5-4d76-986d-aeef54df4d7d.png">

I followed and installed the latest firmware linked in the official Edge Impulse [guide](https://docs.edgeimpulse.com/docs/development-platforms/officially-supported-mcu-targets/espressif-esp32#2.-update-the-firmware). 

> The development board does not come with the right firmware yet. To update the firmware:
> 1. [Download the latest Edge Impulse firmware](https://cdn.edgeimpulse.com/build-system/firmware/espressif-esp32.zip), and unzip the file.
> 2. Open the flash script for your operating system (flash_windows.bat, flash_mac.command or flash_linux.sh) to flash the firmware.
> 3. Wait until flashing is complete.

**Comment by AIWintermuteAI** [comment]
The link in the docs was not updated. I updated it now, check again please.
