### ISSUE TITLE
Microphone Example

### ISSUE THREAD

**Issue by christianfrancouib** [edgeimpulse/firmware-espressif-esp32#4]
Hallo,
My question is if you have a project template to use the microphone. We are using this board for audio purposes firstly. Do you have any template using the microphone?... If not, may you provide some advices to make it work as in the edge impulse demo? 
Thank you,

Christian

**Comment by AIWintermuteAI** [comment]
Hi!
The code for microphone usage is here 
https://github.com/edgeimpulse/firmware-espressif-esp32/blob/main/edge-impulse/ingestion-sdk-platform/sensors/ei_microphone.cpp
we do plan to create Arduino library export for ESP32 in the near future - however microphone usage there won't be vastly different from what you see in the above file.
Hope that answers your question.

**Comment by AIWintermuteAI** [comment]
I'll close the issue due to inactivity.
