### ISSUE TITLE
Build fails, ninja: build stopped: subcommand failed.

### ISSUE THREAD

**Issue by marcusbrostrom** [edgeimpulse/firmware-espressif-esp32#6]
Hello, when cloning the project and building I get a wall of errors that start on step 841/1107 in the building process with idf.py build.
It looks like a linking error but not sure how to solve it. Is anyone familiar to this?
Best regards, Marcus

Terminal output after idf.py build:

[841/1107] Building CXX object esp-idf/main/CMakeFiles/__idf_main.dir/__/edge-impulse-sdk/porting/espressif/ei_classifier_porting.cpp.obj
FAILED: esp-idf/main/CMakeFiles/__idf_main.dir/__/edge-impulse-sdk/porting/espressif/ei_classifier_porting.cpp.obj 
....
....
-conversion -gdwarf-4 -ggdb -mfix-esp32-psram-cache-issue -mfix-esp32-psram-cache-strategy=memw -O2 -fmacro-prefix-map=C:/Users/MarcusPC/Desktop/test_fold/test/firmware-espressif-esp32=. -fmacro-prefix-map=C:/Espressif/frameworks/esp-idf-v5.0=/IDF -fstrict-volatile-bitfields -Wno-error=unused-but-set-variable -fno-jump-tables -fno-tree-switch-conversion -DconfigENABLE_FREERTOS_DEBUG_OCDAWARE=1 -fdiagnostics-color=always -Wno-unused-variable -Wno-maybe-uninitialized -Wno-error=format= -Wno-unused-but-set-parameter -Wno-error=nonnull-compare -Wno-error=stringop-truncation -std=gnu++20 -fno-exceptions -fno-rtti -D_GNU_SOURCE -DIDF_VER=\"v5.0\" -DESP_PLATFORM -D_POSIX_READER_WRITER_LOCKS -O3 -MD -MT esp-idf/main/CMakeFiles/__idf_main.dir/main.cpp.obj -MF esp-idf\main\CMakeFiles\__idf_main.dir\main.cpp.obj.d -o esp-idf/main/CMakeFiles/__idf_main.dir/main.cpp.obj -c C:/Users/MarcusPC/Desktop/test_fold/test/firmware-espressif-esp32/main/main.cpp
In file included from C:/Users/MarcusPC/Desktop/test_fold/test/firmware-espressif-esp32/main/main.cpp:35:
C:/Users/MarcusPC/Desktop/test_fold/test/firmware-espressif-esp32/edge-impulse/ingestion-sdk-platform/sensors/ei_analogsensor.h:51:1: warning: missing initializer for member 'ei_device_fusion_sensor_t::axis_flag_used' [-Wmissing-field-initializers]
   51 | };
      | ^
C:/Users/MarcusPC/Desktop/test_fold/test/firmware-espressif-esp32/main/main.cpp: In function 'int app_main()':
C:/Users/MarcusPC/Desktop/test_fold/test/firmware-espressif-esp32/main/main.cpp:47:5: error: 'gpio_pad_select_gpio' was not declared in this scope; did you mean 'esp_rom_gpio_pad_select_gpio'?
   47 |     gpio_pad_select_gpio(GPIO_NUM_21);
      |     ^~~~~~~~~~~~~~~~~~~~
      |     esp_rom_gpio_pad_select_gpio
In file included from C:/Users/MarcusPC/Desktop/test_fold/test/firmware-espressif-esp32/main/main.cpp:29:
C:/Users/MarcusPC/Desktop/test_fold/test/firmware-espressif-esp32/edge-impulse/ingestion-sdk-platform/espressif_esp32/ei_device_espressif_esp32.h: At global scope:
C:/Users/MarcusPC/Desktop/test_fold/test/firmware-espressif-esp32/edge-impulse/ingestion-sdk-platform/espressif_esp32/ei_device_espressif_esp32.h:113:13: warning: 'bool read_sample_buffer(size_t, size_t, void (*)(uint8_t*, size_t))' declared 'static' but never defined [-Wunused-function]
  113 | static bool read_sample_buffer(size_t begin, size_t length, void (*data_fn)(uint8_t *, size_t));
      |             ^~~~~~~~~~~~~~~~~~
[852/1107] Building CXX object esp-idf/main/CMakeFiles/__idf_main.dir/__/edge-impulse-sdk/dsp/memory.cpp.obj
[853/1107] Building CXX object esp-idf/main/CMakeFiles/__idf_main.dir/__/edge-impulse-sdk/tensorflow/lite/micro/kernels/circular_buffer.cc.obj
[854/1107] Building CXX object esp-idf/main/CMakeFiles/__idf_main.dir/__/edge-impulse-sdk/dsp/dct/fast-dct-fft.cpp.obj
ninja: build stopped: subcommand failed.

**Comment by karla-zamora** [comment]
How did you fix this?
